env:
  variable:
    db:
#      url: jdbc:postgresql://localhost:5432/usa-cities
#      username: postgres
#      password: Karimberdi0309

      url: jdbc:postgresql://autorack.proxy.rlwy.net:57062/railway
      username: postgres
      password: EhxSyzWEdQgPEryklWeTlJTbiYZfCHbJ


openai:
  api:
    url: https://api.openai.com/v1/engines/gpt-4o-mini/completions
    key: sk-mvOdnz6TerEKcGPrpzUHBLOnU6paHX_Dkz7jQ7Bl0kT3BlbkFJze3VbyjDEFD9Uw6udQY-hXDuxlShMFf2PPvNYz3lQA
  model: gpt-4o-mini


api:
  rapid:
    key: 1e0b3fe6d4mshdcf303db614f843p1d2d12jsn54973ae6b34f
    host: google-news13.p.rapidapi.com
